services:
  php:
    container_name: sdk-php-php
    build:
      context: ./
    volumes:
      - .:/app
    working_dir: /app
    command: php -S 0.0.0.0:8000 -t /app
    networks:
      - network

networks:
  network:
    name: sdk-php-network
